[package]
name = "particles"
version = "1.0.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.15", features = [] }
nih = { path = "../../nih" }
image = "0.25"
rand = "0.9"

[build-dependencies]
pkg-config = "0.3"