[package]
name = "texture_filtering"
version = "1.0.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0", features = [] }
nih = { path = "../../nih" }
image = "0.25"

[build-dependencies]
pkg-config = "0.3"