[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.15", features = [] }
wavefront_obj = "11.0.0"
nih = { path = "../nih" }
once_cell = "1.21.3"
parking_lot = "0.12.4"
image = "0.25.6"

[build-dependencies]
pkg-config = "0.3"