name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: NIH2 unit tests
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        toolchain: [ stable, beta, nightly ]
        runner: [ ubuntu-latest, ubuntu-24.04-arm ]
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd nih && cargo test --verbose
      - run: cd nih && cargo test --verbose --release
